apiVersion: apps/v1
kind: Deployment
metadata:
  name: perso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice
  template:
    metadata:
      labels:
        app: myservice
    spec:
      containers:
        - image: corentinnigon/corentinperso:1
          imagePullPolicy: IfNotPresent
          name: corentinperso
      restartPolicy: Always
